name: Fearless Alexa Skill CI/CD
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          cd lambda;
          npm install;
          npm run test;
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ true }}
    steps:
      - name: Checkout and deploy to dev
        uses: actions/checkout@v2
      - run: |
          sudo npm install -g ask-cli@2;
          cd lambda;
          npm install;
      - run: ask deploy
