name: Fearless Alexa Skill CI/CD
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          cd lambda;
          npm install;
          npm run test;
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result=='success' && github.ref == 'refs/head/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Dev
        uses: xavidop/alexa-ask-aws-cli-docker@v1.0.6
      - run: ask deploy
